[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED
    ; -I${PROJECT_DIR}/lib/TFT_eSPI_Config
    ; -include ${PROJECT_DIR}/lib/TFT_eSPI_Config/User_Setup.h
    -include lib/TFT_eSPI/User_Setup.h